# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Fetch and Sync RSS Feeds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  RUN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev -y
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch and Sync RSS Feeds
      run: |
        python bot.py
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PORT: ${{ vars.DB_PORT }}
        MASTODON_HOST: ${{ secrets.MASTODON_HOST }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
